### ISSUE TITLE
NoClassDefFoundError: org/yaml/snakeyaml/error/YAMLException

### ISSUE THREAD

**Issue by Chihsiao** [FlashyReese/CommandAliases#47]
```
[09:44:33] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: org/yaml/snakeyaml/error/YAMLException
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.11.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.19.3-loader.0.14.11-launcher.0.11.1.jar:0.11.1]
Caused by: java.lang.NoClassDefFoundError: org/yaml/snakeyaml/error/YAMLException
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:503) ~[com_fasterxml_jackson_dataformatyaml-2.14.0-c97ca96e0944d734.jar:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:392) ~[com_fasterxml_jackson_dataformatyaml-2.14.0-c97ca96e0944d734.jar:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[com_fasterxml_jackson_dataformatyaml-2.14.0-c97ca96e0944d734.jar:?]
        at com.fasterxml.jackson.databind.ObjectReader.createParser(ObjectReader.java:1077) ~[com_fasterxml_jackson_core_jacksbind-2.14.0-e9915faff784b097.jar:?]
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1653) ~[com_fasterxml_jackson_core_jacksbind-2.14.0-e9915faff784b097.jar:?]
        at me.flashyreese.mods.commandaliases.command.loader.AbstractCommandAliasesProvider.objectMapDataFormat(AbstractCommandAliasesProvider.java:498) ~[commandaliases-1.0.0+mc1.19.3-build.59.jar:?]
        at me.flashyreese.mods.commandaliases.command.loader.AbstractCommandAliasesProvider.loadAndRenderDirectoryTreeLines(AbstractCommandAliasesProvider.java:522) ~[commandaliases-1.0.0+mc1.19.3-build.59.jar:?]
        at me.flashyreese.mods.commandaliases.command.loader.AbstractCommandAliasesProvider.loadAndRenderDirectoryTreeLines(AbstractCommandAliasesProvider.java:534) ~[commandaliases-1.0.0+mc1.19.3-build.59.jar:?]
        at me.flashyreese.mods.commandaliases.command.loader.AbstractCommandAliasesProvider.loadAndRenderDirectoryTree(AbstractCommandAliasesProvider.java:472) ~[commandaliases-1.0.0+mc1.19.3-build.59.jar:?]
        at me.flashyreese.mods.commandaliases.command.loader.AbstractCommandAliasesProvider.loadCommandAliasesFromDirectory(AbstractCommandAliasesProvider.java:443) ~[commandaliases-1.0.0+mc1.19.3-build.59.jar:?]
        at me.flashyreese.mods.commandaliases.command.loader.AbstractCommandAliasesProvider.loadCommandAliases(AbstractCommandAliasesProvider.java:397) ~[commandaliases-1.0.0+mc1.19.3-build.59.jar:?]
        at me.flashyreese.mods.commandaliases.command.loader.CommandAliasesLoader.lambda$registerCommandAliases$0(CommandAliasesLoader.java:58) ~[commandaliases-1.0.0+mc1.19.3-build.59.jar:?]
        at net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:43) ~[fabric-command-api-v2-2.1.16+99f9db8085-10f08566a3c8c4dc.jar:?]
        at net.minecraft.class_2170.handler$zed000$fabric_addCommands(class_2170.java:1548) ~[server-intermediary.jar:?]
        at net.minecraft.class_2170.<init>(class_2170.java:259) ~[server-intermediary.jar:?]
        at net.minecraft.class_5350.<init>(class_5350.java:47) ~[server-intermediary.jar:?]
        at net.minecraft.class_5350.method_29466(class_5350.java:85) ~[server-intermediary.jar:?]
        at net.minecraft.class_7237.method_42098(class_7237.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.method_43612(Main.java:152) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43498(class_156.java:942) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43499(class_156.java:936) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:150) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.11.jar:?]
        ... 4 more
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.error.YAMLException
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:503) ~[com_fasterxml_jackson_dataformatyaml-2.14.0-c97ca96e0944d734.jar:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:392) ~[com_fasterxml_jackson_dataformatyaml-2.14.0-c97ca96e0944d734.jar:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[com_fasterxml_jackson_dataformatyaml-2.14.0-c97ca96e0944d734.jar:?]
        at com.fasterxml.jackson.databind.ObjectReader.createParser(ObjectReader.java:1077) ~[com_fasterxml_jackson_core_jacksbind-2.14.0-e9915faff784b097.jar:?]
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1653) ~[com_fasterxml_jackson_core_jacksbind-2.14.0-e9915faff784b097.jar:?]
        at me.flashyreese.mods.commandaliases.command.loader.AbstractCommandAliasesProvider.objectMapDataFormat(AbstractCommandAliasesProvider.java:498) ~[commandaliases-1.0.0+mc1.19.3-build.59.jar:?]
        at me.flashyreese.mods.commandaliases.command.loader.AbstractCommandAliasesProvider.loadAndRenderDirectoryTreeLines(AbstractCommandAliasesProvider.java:522) ~[commandaliases-1.0.0+mc1.19.3-build.59.jar:?]
        at me.flashyreese.mods.commandaliases.command.loader.AbstractCommandAliasesProvider.loadAndRenderDirectoryTreeLines(AbstractCommandAliasesProvider.java:534) ~[commandaliases-1.0.0+mc1.19.3-build.59.jar:?]
        at me.flashyreese.mods.commandaliases.command.loader.AbstractCommandAliasesProvider.loadAndRenderDirectoryTree(AbstractCommandAliasesProvider.java:472) ~[commandaliases-1.0.0+mc1.19.3-build.59.jar:?]
        at me.flashyreese.mods.commandaliases.command.loader.AbstractCommandAliasesProvider.loadCommandAliasesFromDirectory(AbstractCommandAliasesProvider.java:443) ~[commandaliases-1.0.0+mc1.19.3-build.59.jar:?]
        at me.flashyreese.mods.commandaliases.command.loader.AbstractCommandAliasesProvider.loadCommandAliases(AbstractCommandAliasesProvider.java:397) ~[commandaliases-1.0.0+mc1.19.3-build.59.jar:?]
        at me.flashyreese.mods.commandaliases.command.loader.CommandAliasesLoader.lambda$registerCommandAliases$0(CommandAliasesLoader.java:58) ~[commandaliases-1.0.0+mc1.19.3-build.59.jar:?]
        at net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:43) ~[fabric-command-api-v2-2.1.16+99f9db8085-10f08566a3c8c4dc.jar:?]
        at net.minecraft.class_2170.handler$zed000$fabric_addCommands(class_2170.java:1548) ~[server-intermediary.jar:?]
        at net.minecraft.class_2170.<init>(class_2170.java:259) ~[server-intermediary.jar:?]
        at net.minecraft.class_5350.<init>(class_5350.java:47) ~[server-intermediary.jar:?]
        at net.minecraft.class_5350.method_29466(class_5350.java:85) ~[server-intermediary.jar:?]
        at net.minecraft.class_7237.method_42098(class_7237.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.method_43612(Main.java:152) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43498(class_156.java:942) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43499(class_156.java:936) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:150) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.11.jar:?]
        ... 4 more
```

**Comment by FlashyReese** [comment]
I was made aware of this issue recently, it's already been fixed in https://github.com/FlashyReese/CommandAliases/commit/44c88ee30c565e7e7cc1edc521094aaef67bafda. It will be in the next release.
