### ISSUE TITLE
Server crashes after i reload the mod

### ISSUE THREAD

**Issue by CoreBytee** [FlashyReese/CommandAliases#9]
this is my crash report:

[11:18:22] [Server thread/INFO]: [CoreBytes: Reloading all Command Aliases!]
[11:18:22] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/class_5473
	at me.flashyreese.mods.commandaliases.classtool.impl.argument.ArgumentTypeManager.registerArgumentTypes(ArgumentTypeManager.java:194) ~[commandaliases-0.4.0.jar:?]
	at me.flashyreese.mods.commandaliases.classtool.impl.argument.ArgumentTypeManager.<init>(ArgumentTypeManager.java:45) ~[commandaliases-0.4.0.jar:?]
	at me.flashyreese.mods.commandaliases.command.builders.CommandAliasesBuilder.<init>(CommandAliasesBuilder.java:59) ~[commandaliases-0.4.0.jar:?]
	at me.flashyreese.mods.commandaliases.CommandAliasesLoader.registerCommands(CommandAliasesLoader.java:76) ~[commandaliases-0.4.0.jar:?]
	at me.flashyreese.mods.commandaliases.CommandAliasesLoader.lambda$registerCommandAliasesCommands$4(CommandAliasesLoader.java:125) ~[commandaliases-0.4.0.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[intermediary-server.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176) ~[intermediary-server.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:260) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_14370(class_3244.java:1134) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_12048(class_3244.java:1121) ~[intermediary-server.jar:?]
	at net.minecraft.class_2797.method_12115(class_2797.java:36) ~[intermediary-server.jar:?]
	at net.minecraft.class_2797.method_11054(class_2797.java:9) ~[intermediary-server.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:724) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zjf000$modifiedRunLoop(MinecraftServer.java:2805) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:653) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_5473
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	... 27 more
[11:18:22] [Server thread/ERROR]: This crash report has been saved to: /home/mc-server/run/./crash-reports/crash-2021-01-30_11.18.22-server.txt
[11:18:22] [Server thread/INFO]: Stopping server
[11:18:22] [Server thread/INFO]: Saving players

and this is my config file: 

{
	"commandMode": "COMMAND_ALIAS",
	"command": "helpop {arg::greedy_string#message}",
	"execution": [
		{
			"command": "execute if entity @a[team=Staff] run tellraw @a[team=Staff] [\"\",{\"text\":\"[\",\"color\":\"gold\"},{\"text\":\"HelpOP\",\"color\":\"dark_red\"},{\"text\":\"] \",\"color\":\"gold\"},{\"text\":\"{this::SELF}\",\"color\":\"red\"},{\"text\":\": \",\"color\":\"white\"},{\"text\":\"{message}\",\"color\":\"red\"}]",
			"type": "SERVER",
			"ignoreOptionalRemoval": true
		},
		{
			"command": "execute unless entity @a[team=Staff] run tellraw {this::SELF} [\"\",{\"text\":\"[\",\"color\":\"gold\"},{\"text\":\"HelpOP\",\"color\":\"dark_red\"},{\"text\":\"] \",\"color\":\"gold\"},{\"text\":\"There are currently no staff online!\",\"color\":\"red\"}]",
			"type": "SERVER",
			"sleep": "1000"
		},
		{
			"command": "execute unless entity @a[team=Staff] run tellraw {this::SELF} [\"\",{\"text\":\"[\",\"color\":\"gold\"},{\"text\":\"HelpOP\",\"color\":\"dark_red\"},{\"text\":\"] \",\"color\":\"gold\"},{\"text\":\"You can get help in our discord:\",\"color\":\"red\"},{\"text\":\"\\n\"},{\"text\":\"URL GOES HERE\",\"color\":\"gold\",\"clickEvent\":{\"action\":\"open_url\",\"value\":\"URL GOES HERE\"}}]",
			"type": "SERVER"
		}
	]
}

(Just copied that from the wiki)

**Comment by FlashyReese** [comment]
Your config file is invalid and not formatted correctly.

`commandaliases.json` should look like this
```json
[
	{
		"commandMode": "COMMAND_ALIAS",
		"command": "helpop {arg::greedy_string#message}",
		"execution": [
			{
				"command": "execute if entity @a[team=Staff] run tellraw @a[team=Staff] [\"\",{\"text\":\"[\",\"color\":\"gold\"},{\"text\":\"HelpOP\",\"color\":\"dark_red\"},{\"text\":\"] \",\"color\":\"gold\"},{\"text\":\"{this::SELF}\",\"color\":\"red\"},{\"text\":\": \",\"color\":\"white\"},{\"text\":\"{message}\",\"color\":\"red\"}]",
				"type": "SERVER",
				"ignoreOptionalRemoval": true
			},
			{
				"command": "execute unless entity @a[team=Staff] run tellraw {this::SELF} [\"\",{\"text\":\"[\",\"color\":\"gold\"},{\"text\":\"HelpOP\",\"color\":\"dark_red\"},{\"text\":\"] \",\"color\":\"gold\"},{\"text\":\"There are currently no staff online!\",\"color\":\"red\"}]",
				"type": "SERVER",
				"sleep": "1000"
			},
			{
				"command": "execute unless entity @a[team=Staff] run tellraw {this::SELF} [\"\",{\"text\":\"[\",\"color\":\"gold\"},{\"text\":\"HelpOP\",\"color\":\"dark_red\"},{\"text\":\"] \",\"color\":\"gold\"},{\"text\":\"You can get help in our discord:\",\"color\":\"red\"},{\"text\":\"\\n\"},{\"text\":\"URL GOES HERE\",\"color\":\"gold\",\"clickEvent\":{\"action\":\"open_url\",\"value\":\"URL GOES HERE\"}}]",
				"type": "SERVER"
			}
		]
	}
]
```

**Comment by CoreBytee** [comment]
still gives a crash

**Comment by FlashyReese** [comment]
Can you provide the list of installed mods, minecraft versions and a complete log(can you upload to [pastebin](https://pastebin.com/) or [GitHub's Gist](https://gist.github.com/))?

**Comment by CoreBytee** [comment]
Sorry, i just updated my server to 1.16.4 (i was on 1.16.1) and its working now!
Thanks for the help!
